version: "{build}"
os: Windows Server 2012 R2
test: off

clone_folder: c:\gopath\src\github.com\regner\amdr-client

environment:
  GOPATH: c:\gopath
  
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;%PATH%
  - go version
  - go env

build_script:
  - go get
  - set GOARCH=386
  - go build -o amdr.exe --ldflags main.go
